package:
  name: rosetta

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - hdf5=1.8

  host:
    - zlib

  run:
    - zlib
    - hdf5=1.8

test:
  commands:
    - rosetta_scripts

about:
  home: http://rosettacommons.org
