package:
  name: pyrosetta-binder

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  run:
    - python

test:
  commands:
    - pyrosetta-binder --help


about:
  home: https://github.com/rosettacommons/binder
